config/routes.rb
Rails.application.routes.draw do
  get "form",  to: 'rsvp#question_1'
  get "formulaire" , to: 'rsvp#question_2'
  get "invitation" , to: 'rsvp#question_3'
  post "answer_1", to: "rsvp#answer_1"
  post "answer_2", to: "rsvp#answer_2"
  root to: 'pages#home'
  get 'practical_information', to: 'pages#practical_information'
  get 'wedding_list', to: 'pages#wedding_list'
  get 'qa', to: 'pages#qa'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rsvp_controller.rb
class RsvpController < ApplicationController
  def question_1
  end

  def question_2
  end

  def answer_1
    RspAnswerMailer.with(form: params[:form]).answer_1.deliver_now
    redirect_to root_path
    end

  def answer_2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Malo&Seb</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.8.5/jquery-ui.min.js" integrity="sha256-fOse6WapxTrUSJOJICXXYwHRJOPa6C1OUQXi7C9Ddy8=" crossorigin="anonymous"></script>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    
    <%= javascript_include_tag 'application' %>

  </head>
  <body>
    <%= render 'shared/navbar' %>  
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="forMWeb">
    <div class="mWebImg">
        <%= image_tag  "openInWeb.svg", :class => "img-responsive" %>
    </div>
</div>
<div class="mainOpening onlyWebLoad" id="introAnimation" onclick="introAnimation()">
    <div class="invitationText" id="couponAnimation">
        <div style="display: flex; flex-direction: column; align-items:center; justify-content:center;">
        <%= image_tag  "together-with-your-family.svg" %>
        <p onclick="introAnimation()" class="clickHere" style="color: #323159;" id="clickHere"> Continue to website <p>
        </div>
    </div>
    <div class="layer1 imgLayer" id="leafLayer1">
        <%= image_tag  "layer1.svg" %>
    </div>
    <div class="layer2 imgLayer" id="leafLayer2">
        <%= image_tag  "layer2.svg" %>
    </div>
    <div class="layer3 imgLayer" id="leafLayer3">
        <%= image_tag  "layer3.svg" %>
    </div>
    <div class="layer4" id="bgLayerAnimation"></div>
</div>
<div class="theContainer">
            <div class="mainImages clickThrough">
                <div class="bottomLeftImg">
                    <%= image_tag  "hornBill.svg" %>
                </div>
                <div class="topRightImg">
                    <%= image_tag  "leaves.svg" %>
                </div>
            </div>
            <div class="mainContainer">
                <div class="container-fluid no-padding">
                    <div class="row">
                        <div class="col-md-6 no-padding">
                            <div class="leftSide lightGreen">
                                <div class="onlymWeb">
                                    <%= image_tag  "name-mWeb.svg", :class => "mWebNameImage" %>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 no-padding onlyWebLoad">
                            <div class="rightSide">
                                <%= image_tag  "name.svg", :class => "onlyWebLoad" %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<script type="text/javascript">

function introAnimation() {
    document.getElementById("leafLayer1").classList.add("leafAnimation1");
    document.getElementById("leafLayer2").classList.add("leafAnimation2");
    document.getElementById("leafLayer3").classList.add("leafAnimation3");
    document.getElementById("couponAnimation").classList.add("couponAnimation");
    document.getElementById("bgLayerAnimation").classList.add("couponAnimation");
    document.getElementById("clickHere").classList.add("noOpacity");

    var delayInMilliseconds = 4000;

    setTimeout(function() {
        document.getElementById("introAnimation").classList.add("invisible");
    }, delayInMilliseconds);
    };

</script>

app/views/pages/practical_information.html.erb
<div class="theContainer">
    <div class="mainImages clickThrough">
        <div class="bottomLeftImg">
            <%= image_tag  "hornBill.svg" %>
        </div>
        <div class="topRightImg">
            <%= image_tag  "leaves.svg" %>
        </div>
    </div>
    <div class="mainContainer">
        <div class="container-fluid no-padding">
            <div class="row">
                <div class="col-md-6 no-padding">
                    <div class="leftSide pinkBG">
                        <div class="onlymWeb">
                            <div class="scheduleContainer">
                                <br><br><br>
                                <div class="titleText pinkText">Practical Information</div>
                                <br><br>
                                <p>We would love to have you by our side to celebrate our love!</p>
                                <br><br>
                                <p class="secondaryTitleText pinkText">When?</p>
                                <br>
                                <div class="pinkText saturday">Saturday, 05 October</div>
                                <br><br>
                                <p>2:00 pm - 3:15 pm: Wedding ceremony</br>4:00 pm - 6:30 pm: Reception</br>7:00 pm - 22:30 pm: Seated dinner</br>22:30 pm - wee hours: PARTY</p>
                                <br><br>
                                <p class="secondaryTitleText pinkText">Where?</p>
                                <br>
                                <p>Wedding ceremony : Eglise Saint-Martin, 1390 GREZ-DOICEAU, BELGIUM</p>
                                <br>
                                <p>From the Reception onwards : la ferme d'Arnelle - Rue de Sart Risbart 40, 1325 LONGUEVILLE, BELGIUM</p>
                                <br>
                                <div style="display: flex; align-items: left; flex-direction: column;">
                                    <div class="secondaryTitleText pinkText" >How to get there?</div>
                                    <br><br>
                                    <div style="display:flex; flex-direction: column; justify-content: center;">
                                        <div style="display:flex; justify-content: left; align-items: center;">
                                            <i class="fas fa-car gettingthereIconMedium"></i>
                                            <p class="">By car to l'Eglise Saint Martin & to la ferme d’Arnelle (30 min from Brussels)</p>
                                        </div>
                                        <div style="display:flex; justify-content: left; align-items: center;">
                                            <i class="fas fa-bus gettingthereIconMedium"></i>
                                            <p class="">A shuttle bus will be organised from Delta, Auderghem at 1:00 pm sharp and will bring you back to Delta around 4:00am. It will drive you from the wedding ceremony to the wedding venue.</p>
                                        </div>
                                        <p style="font-size: 12px"> *Make sure to specify if you want to use the shuttle bus when you RSVP. </p>
                                        <p style="font-size: 12px"> *Please note: first come, first served, as there are a limited number of seats. </p>
                                    </div>
                                </div>
                                <div style="display:flex; justify-content: center; align-items: center;">
                                    <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1ZPY6a92jATNtUraiSc5RZG8ym6TWGvGH" style="border:10px solid white;" width="350" height="400"></iframe>
                                </div>
                                <br><br><br><br><br><br><br><br><br>
                            
                            
                            </div>  
                        </div>
                    </div>
                </div>
                <div class="col-md-6 no-padding onlyWebLoad">
                    <div class="rightSide">
                        
                        <div class="scheduleContainer">
                            <br><br><br>
                            <div class="titleText pinkText">Practical Information</div>
                            <br><br>
                            <p>We would love to have you by our side to celebrate our love!</p>
                            <br><br>
                            <p class="secondaryTitleText pinkText">When?</p>
                            <br>
                            <p class="pinkText">Saturday, 05 October</p>
                            <br><br>
                            <p>2:00 pm - 3:15 pm: Wedding ceremony</br>4:00 pm - 6:30 pm: Reception</br>7:00 pm - 22:30 pm: Seated dinner</br>22:30 pm - wee hours: PARTY</p>
                            <br><br>
                            <p class="secondaryTitleText pinkText">Where?</p>
                            <br>
                            <p>Wedding ceremony : Eglise Saint-Martin, 1390 GREZ-DOICEAU, BELGIUM</p>
                            <br>
                            <p>From the Reception onwards : la ferme d'Arnelle - Rue de Sart Risbart 40, 1325 LONGUEVILLE, BELGIUM</p>
                            <br>
                            <div style="display: flex; align-items: left; flex-direction: column;">
                                <div class="secondaryTitleText pinkText" >How to get there?</div>
                                <br><br>
                                <div style="display:flex; flex-direction: column; justify-content: center;">
                                    <div style="display:flex; justify-content: left; align-items: center;">
                                        <i class="fas fa-car gettingthereIconMedium"></i>
                                        <p class="">By car to l'Eglise Saint Martin & to la ferme d’Arnelle (30 min from Brussels)</p>
                                    </div>
                                    <div style="display:flex; justify-content: left; align-items: center;">
                                        <i class="fas fa-bus gettingthereIconMedium"></i>
                                        <p class="">A shuttle bus will be organised from Delta, Auderghem at 1:00 pm sharp and will bring you back to Delta around 4:00am. It will drive you from the wedding ceremony to the wedding venue.</p>
                                    </div>
                                    <p style="font-size: 16px"> *Make sure to specify if you want to use the shuttle bus when you RSVP. </p>
                                    <p style="font-size: 16px"> *Please note: first come, first served, as there are a limited number of seats. </p>
                                </div>
                            </div>
                            <div style="display:flex; justify-content: center; align-items: center;">
                                <iframe src="https://www.google.com/maps/d/u/0/embed?mid=1ZPY6a92jATNtUraiSc5RZG8ym6TWGvGH" style="border:10px solid white;" width="500" height="400"></iframe>
                            </div>
                            <br><br>
                            <br><br><br><br><br><br><br><br><br>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/qa.html.erb
<div class="theContainer">
    <div class="mainImages clickThrough">
        <div class="bottomLeftImg">
            <%= image_tag  "hornBill.svg" %>
        </div>
        <div class="topRightImg">
            <%= image_tag  "leaves.svg" %>
        </div>
    </div>
    <div class="mainContainer">
        <div class="container-fluid no-padding">
            <div class="row">
                <div class="col-md-6 no-padding">
                    <div class="leftSide darkBlueBG">
                        <div class="onlymWeb">
                            <div class="scheduleContainer">
                                <br><br><br>
                            <div class="titleText darkBlueText">Q&A</div>
                            <br><br><br><br>
                            <p class="secondaryTitleText darkBlueText">Dress code?</p>
                            <br>
                            <p>Tenue de ville</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">Are kids welcome?</p>
                            <br>
                            <p>Our preference would be to have your undivided attention that day. However, if you really want or need to bring your kid(s) please note there is an unsupervised stretch of water. </p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">What is the deadline to answer?</p>
                            <br>
                            <p>The deadline to respond via the form linked in the email is the 30th of August. Past this date you're still welcome to participate, just advised to bring a chair and some sandwiches <i class="far fa-smile-wink"></i> </p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">May I bring my date?</p>
                            <br>
                            <p>Please email us at MaloetSeb2019@gmail.com to submit an application with pictures and cover letter.</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">Where should I park?</p>
                            <br>
                            <p>For the wedding ceremony, there is a public parking in front of l’Eglise Saint-Martin.
                            </br>For the wedding venue, next to the entrance of la ferme d’Arnelle, someone will guide you to a parking spot.</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">What if I have dietary restrictions?</p>
                            <br>
                            <p>Contact us at MaloetSeb2019@gmail.com.</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">Is the wedding indoors or outdoors?</p>
                            <br>
                            <p>The ceremony and dinner will be indoors, while the reception will be outdoors. So in case of chilly weather bring some layers.
                            </br>We would be forever grateful if you could pray for sun and heat :)
                            <br><br>
                            <p class="secondaryTitleText darkBlueText">More questions ?</p>
                            <br>
                            <p>Please do not hesitate to contact us at MaloetSeb2019@gmail.com should you have any further questions or comments.</p>
                            <br>
                            <br><br><br><br><br><br><br>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-md-6 no-padding onlyWebLoad">
                    <div class="rightSide">
                        
                        <div class="scheduleContainer">
                             <br><br><br>
                            <div class="titleText darkBlueText">Q&A</div>
                            <br><br><br><br>
                            <p class="secondaryTitleText darkBlueText">Dress code?</p>
                            <br>
                            <p>Tenue de ville</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">Are kids welcome?</p>
                            <br>
                            <p>Our preference would be to have your undivided attention that day. However, if you really want or need to bring your kid(s) please note there is an unsupervised stretch of water. </p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">What is the deadline to answer?</p>
                            <br>
                            <p>The deadline to respond via the form linked in the email is the 30th of August. Past this date you're still welcome to participate, just advised to bring a chair and some sandwiches <i class="far fa-smile-wink"></i></p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">May I bring my date?</p>
                            <br>
                            <p>Please email us at MaloetSeb2019@gmail.com to submit an application with pictures and cover letter.</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">Where should I park?</p>
                            <br>
                            <p>For the wedding ceremony, there is a public parking in front of l’Eglise Saint-Martin.
                            </br>For the wedding venue, next to the entrance of la ferme d’Arnelle, someone will guide you to a parking spot.</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">What if I have dietary restrictions?</p>
                            <br>
                            <p>Contact us at MaloetSeb2019@gmail.com.</p>
                            <br>
                            <p class="secondaryTitleText darkBlueText">Is the wedding indoors or outdoors?</p>
                            <br>
                            <p>The ceremony and dinner will be indoors, while the reception will be outdoors. So in case of chilly weather bring some layers.
                            </br>We would be forever grateful if you could pray for sun and heat :)
                            <br><br>
                            <p class="secondaryTitleText darkBlueText">More questions ?</p>
                            <br>
                            <p>Please do not hesitate to contact us at MaloetSeb2019@gmail.com should you have any further questions or comments.</p>
                            <br>
                            <br><br><br><br><br><br><br>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/wedding_list.html.erb
<div class="theContainer">
    <div class="mainImages clickThrough">
        <div class="bottomLeftImg">
            <%= image_tag  "hornBill.svg" %>
        </div>
        <div class="topRightImg">
            <%= image_tag  "leaves.svg" %>
        </div>
    </div>
    <div class="mainContainer">
        <div class="container-fluid no-padding">
            <div class="row">
                <div class="col-md-6 no-padding">
                    <div class="leftSide lightBlueBG">
                        <div class="onlymWeb">
                             <div class="scheduleContainer">
                                <br><br><br>
                                <div class="titleText lightBlueText">Wedding List</div>
                                <br><br>
                                <p>Dearest friends and family,
                                </br><br>
                                Your presence is the most beautiful gift! 
                                </br>
                                Should you however wish to participate in getting us set up for life post-wedding, 
                                the following link will help you to contribute towards our happy life together 
                                </br><br>
                                <a href="https://wecocoon.com/fr/registry/MaloSeb" target="_blank">Wedding List</a>
                                </br>
                                <br><br>
                                All our love,</br>
                                Malo & Seb</br>
                                <br>
                                Thank you!
                                </p>
                                <br><br><br><br><br><br><br>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-md-6 no-padding onlyWebLoad">
                    <div class="rightSide">
                        
                        <div class="scheduleContainer">
                            <br><br><br>
                            <div class="titleText lightBlueText">Wedding List</div>
                            <br><br>
                            <p>Dearest friends and family,
                            </br><br>
                            Your presence is the most beautiful gift! 
                            </br>
                            Should you however wish to participate in getting us set up for life post-wedding, 
                            the following link will help you to contribute towards our happy life together : 
                            </br><br>
                            <a href="https://wecocoon.com/fr/registry/MaloSeb" target="_blank">Wedding List</a>
                            </br>
                            <br><br>
                            All our love,</br>
                            Malo & Seb</br>
                            <br>
                            Thank you!
                            </p>
                            <br><br><br><br><br><br><br>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/rsvp/question_3.html.erb
<div class="theContainer">
    <div class="mainImages clickThrough">
        <div class="bottomLeftImg">
            <%= image_tag  "hornBill.svg" %>
        </div>
        <div class="topRightImg">
            <%= image_tag  "leaves.svg" %>
        </div>
    </div>
    <div class="mainContainer">
        <div class="container-fluid no-padding">
            <div class="row">
                <div class="col-md-6 no-padding">
                    <div class="leftSide lightBlueBG">
                        <div class="onlymWeb">
                             <div class="formContainer">
                                
                                <br><br><br><br><br><br><br><br>
                            <div class="formInfoContainer">
                                <p>Together with their parents
                                </br>Marie-Laure Léonard & Sebastiaan Claes 
                                </br>Request the honor of your presence at their marriage</p>
                                <br>
                                <p>At l’Eglise Saint-Martin
                                </br>Saturday, October 5th, 2019
                                </br>2.00 o’clock in the afternoon
                                </br>1390 GREZ-DOICEAU, BELGIUM</p>
                                <br>
                                <p class="titleText">Reception</p>
                                <p>Mrs François Léonard
                                </br>Mrs André Claes
                                </br>request the pleasure of your company at la ferme d’Arnelle 
                                </br>On Saturday, October 5th from 4.00 to 6.30 pm</p>
                                <br>
                            </div>
                            <br><br><br>
                            <%= form_for :form, url: answer_1_path  do |f|%>
                                <div class="flexRow">
                                    <div class="flexRowItem">
                                        <%= f.label :prenom, 'First Name(s)'%>
                                        <%= f.text_field :prenom %>
                                    </div>
                                    <div style="width: 10px;"></div>
                                    <div class="flexRowItem">
                                        <%= f.label :nom, 'Last Name(s)'%>
                                        <%= f.text_field :nom %>    
                                    </div>
                                </div>
                                <br><br>
                                <div style="display: flex; justify-content: center;">
                                    <p style="font-size: 24px;">Will you be attending?</p>
                                </div>
                                <br><br>
                                <div class="flexRowCheckbox">
                                    <%= f.label :RECEPTION, 'Reception' %>
                                    <%= f.check_box "RECEPTION", label: "reception"  %>
                                </div>
                                <br>
                                <div class="formSubmit">
                                    <%= f.submit "Confirm Invitation"%>
                                <div>
                            <% end %>

                        <br><br><br><br><br><br><br><br><br><br><br><br>
                        </div>
                        </div>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6 no-padding onlyWebLoad">
                    <div class="rightSide">
                        <br><br><br><br><br><br><br><br>
                        <div class="formContainer">
                        <br><br><br><br><br><br><br><br>
                            <div class="formInfoContainer">
                                <p>Together with their parents
                                </br>Marie-Laure Léonard & Sebastiaan Claes 
                                </br>Request the honor of your presence at their marriage</p>
                                <br>
                                <p>At l’Eglise Saint-Martin
                                </br>Saturday, October 5th, 2019
                                </br>2.00 o’clock in the afternoon
                                </br>1390 GREZ-DOICEAU, BELGIUM</p>
                                <br>
                                <p class="titleText">Reception</p>
                                <p>Mrs François Léonard
                                </br>Mrs André Claes
                                </br>Request the pleasure of your company at la ferme d’Arnelle
                                </br>On Saturday, October 5th from 4.00 to 6.30 pm</p>
                                <br>
                            </div>
                            <br><br><br>
                            <%= form_for :form, url: answer_1_path  do |f|%>
                                <div class="flexRow">
                                    <div class="flexRowItem">
                                        <%= f.label :prenom, 'First Name(s)'%>
                                        <div style="width: 10px;"></div>
                                        <%= f.text_field :prenom %>
                                    </div>
                                    <div class="flexRowItem">
                                        <%= f.label :nom, 'Last Name(s)'%>
                                        <%= f.text_field :nom %>    
                                    </div>
                                </div>
                                <br><br>
                                 <div style="display: flex; justify-content: center;">
                                    <p style="font-size: 24px;">Will you be attending?</p>
                                </div>
                                <br><br>
                                <div class="flexRowCheckbox">
                                    <%= f.label :RECEPTION, 'Reception' %>
                                    <%= f.check_box "RECEPTION", label: "reception"  %>
                                </div>
                                <br>
                                <div class="formSubmit">
                                    <%= f.submit "Confirm Invitation"%>
                                <div>
                            <% end %>

                        <br><br><br><br><br><br><br><br>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navBar" id="navBar" >
    <div class="navbarText">
        <%= link_to "Home", root_path %>
        <%= link_to "Practical Information", practical_information_path %>
        <%= link_to "Wedding List", wedding_list_path %>
        <%= link_to "Q & A", qa_path %>
    </div>
    <br>
    <div class="navbarArrow arrowRemove arrowAnimate" onclick="navBar()" style="cursor: pointer;">
        <p id="navbarAidText">NAVIGATION</p>
        <i id="navbarArrow" class="fas fa-angle-down"></i>
    </div>
</div>

<script type="text/javascript">

function navBar() {
    document.getElementById("navBar").classList.toggle("moveDown");
    document.getElementById("navbarArrow").classList.toggle("flip");
}

</script>

<div class="mobileMenuButton" onclick="mobileMenu()">
    <i class="fas fa-bars"></i>
</div>
<div class="mobileMenuButton" onclick="mobileMenuClose()" id="closeCross">
    <i class="fas fa-times"></i>
</div>

<div id="navBarMobile" >
    <div class="navbarMobileText">
       <%= link_to "Home", root_path %>
        <%= link_to "Practical Information", practical_information_path %>
        <%= link_to "Wedding List", wedding_list_path %>
        <%= link_to "Q & A", qa_path %>
        <br><br><br>
    </div>
</div>

<script type="text/javascript">

function mobileMenu() {
    document.getElementById("navBarMobile").classList.toggle("moveRight");
    document.getElementById("closeCross").classList.toggle("getVisible");
}

function mobileMenuClose() {
    document.getElementById("navBarMobile").classList.toggle("moveRight");
    document.getElementById("closeCross").classList.toggle("getVisible");
}

</script>